version: '3'

volumes:
  django_db_dev: {}

services:
  db:
    image: postgres
    volumes: 
      - django_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pyeon
      - POSTGRES_USER=pyeonuser
      - POSTGRES_PASSWORD=pyeonpassword

  django:
    build: 
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=pyeon
      - DJANGO_DB_USERNAME=pyeonuser
      - DJANGO_DB_PASSWORD=pyeonpassword
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command: >
      bash -c "
      chmod +x /wait-for-it.sh
      && /wait-for-it.sh db:5432 -t 10
      && python manage.py makemigrations member assignment attendance lecture management notice reference
      && python manage.py migrate
      && python manage.py runserver 0:8000
      "
    # && python manage.py makemigrations member assignment attendance lecture management notice reference  
    # && python manage.py migrate --fake admin zero  #remove django pyeon_air migration file  
    # && python manage.py migrate member assignment attendance lecture management notice reference --fake
    # && python manage.py runserver 0:8000
    # && python manage.py runserver react # 이게 안먹는 이유는 react와 관련 있을 듯. 
    volumes:
      - ./:/project/
  react:
    build: 
      context: .
      dockerfile: ./compose/react/Dockerfile-react
    volumes:
      - /project/frontend/reactapp/node_modules
      - ./frontend/reactapp:/project/frontend/reactapp
    ports:
      - "3000:3000"
    command: ['npm', 'start']
