# Generated by Django 3.2.11 on 2022-02-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureInfo',
            fields=[
                ('lecture_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('lecture_type', models.CharField(max_length=20)),
                ('lecture_link', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('lecture_start_at', models.DateTimeField()),
                ('lecture_end_at', models.DateTimeField()),
                ('company_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_assignment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LectureAttendLog',
            fields=[
                ('lecture_log_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('account_id', models.IntegerField()),
                ('progress_rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attend_log', to='lecture.lectureinfo')),
            ],
        ),
    ]
