# Generated by Django 3.2.11 on 2022-02-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('course_id', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Companylist',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account_login_log',
            fields=[
                ('login_log_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_login_log', to='member.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.ForeignKey(db_column='company_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='member.companylist'),
        ),
    ]
