# Generated by Django 3.2.11 on 2022-02-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MA', 'Master'), ('ST', 'Student'), ('TE', 'Teacher'), ('AS', 'Assistant')], max_length=2),
        ),
    ]
