FROM python:3

ENV PYTHONUNBUFFERED=1

WORKDIR /project

COPY requirements.txt /project/
RUN pip install -r requirements.txt

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /
# CMD ['python' 'manage.py' 'runserver' 'react']