# Generated by Django 3.2.11 on 2022-02-22 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_title', models.CharField(max_length=50)),
                ('question_content', models.CharField(max_length=1000)),
                ('is_answered', models.BooleanField(default=False)),
                ('question_user_name', models.IntegerField()),
                ('answer_user_name', models.IntegerField()),
                ('answer_content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('attachment_url', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
