# Generated by Django 3.2.11 on 2022-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('attachment_url', models.CharField(max_length=255)),
                ('account_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_title', models.CharField(max_length=50)),
                ('question_content', models.CharField(max_length=1000)),
                ('is_answered', models.BooleanField(default=False)),
                ('question_account_id', models.IntegerField()),
                ('answer_account_id', models.IntegerField()),
                ('answer_content', models.CharField(max_length=1000)),
            ],
        ),
    ]
