# Generated by Django 3.2.11 on 2022-02-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_create_info',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('assignment_info', models.CharField(max_length=500)),
                ('assignment_start_at', models.DateTimeField()),
                ('assignment_end_at', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('attachment_url', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='member.account')),
            ],
        ),
    ]
