# Generated by Django 3.2.11 on 2022-02-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '__first__'),
        ('member', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentCreateInfo',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('assignment_info', models.CharField(max_length=500)),
                ('assignment_start_at', models.DateTimeField()),
                ('assignment_end_at', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('attachment_url', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_account_id', to='member.account')),
                ('lecture_id', models.ForeignKey(db_column='lecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_lecture_id', to='lecture.lectureinfo')),
            ],
        ),
    ]
