# Generated by Django 3.2.11 on 2022-02-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0001_initial'),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_create_info',
            name='lecture_id',
            field=models.ForeignKey(db_column='lecture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='lecture.lecture_info'),
        ),
    ]
