# Generated by Django 3.2.11 on 2022-02-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_out_log',
            fields=[
                ('in_out_log_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_at', models.DateTimeField(auto_now=True)),
                ('out_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_out_log', to='member.account')),
            ],
        ),
    ]
