# Generated by Django 3.2.11 on 2022-02-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrInfo',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('qr_category', models.CharField(choices=[('IN', 'check in'), ('OUT', 'check out')], default='IN', max_length=3)),
                ('start_date', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('qr_content', models.CharField(max_length=50)),
                ('qr_notice', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'QR table',
                'ordering': [],
            },
        ),
    ]
