# Generated by Django 3.2.11 on 2022-02-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_qrinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrinfo',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='qrinfo',
            name='start_time',
        ),
    ]
